name: ATMS523-Final3.13
channels:
  - conda-forge
  - pkgs/main
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aom=3.9.1=he0c23c2_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=pyhcf101f3_1
  - blosc=1.21.6=hfd34d9b_1
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.0=h91e5215_2
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cf_xarray=0.10.9=pyhd8ed1ab_0
  - cffi=2.0.0=py313h5ea7bf4_1
  - cfgrib=0.9.15.1=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py313hf069bd2_3
  - cpython=3.13.10=py313hd8ed1ab_100
  - cycler=0.12.1=pyhcf101f3_2
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.17=py313h927ade5_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - eccodes=2.40.0=h4f3607b_0
  - esmf=8.4.2=nompi_hee46c9f_3
  - esmpy=8.4.2=pyhc1e730c_4
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h885b0b7_1
  - findlibs=0.1.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.0=py313hd650c13_0
  - freeglut=3.8.0=hfcef157_0
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - geos=3.14.1=hdade9fe_0
  - graphite2=1.3.14=hac47afa_2
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf4=4.2.15=h1b1b6ef_5
  - hdf5=1.14.3=nompi_hb2c4d47_109
  - icu=73.2=h63175ca_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.8.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jasper=4.2.4=ha9f4a2c_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jpeg=9e=hcfcfb64_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - kiwisolver=1.4.9=py313h1a38498_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libaec=1.1.4=h20038f6_0
  - libavif=1.3.0=he916da2_2
  - libavif16=1.3.0=he916da2_2
  - libblas=3.11.0=4_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=4_h2a3cdd5_mkl
  - libclang13=21.1.7=default_ha2db4b5_1
  - libcurl=8.17.0=h43ecb02_0
  - libdeflate=1.22=h2466b09_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=h885b0b7_1
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libglib=2.84.4=hfaec014_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.18=hc1393d2_2
  - libkrb5=1.21.3=h885b0b7_4
  - liblapack=3.11.0=4_hf9ab0e9_mkl
  - libmpdec=4.0.0=h827c3e9_0
  - libnetcdf=4.9.2=nompi_h008f77d_116
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.51=h7351971_0
  - libpq=17.6=h652a1e2_0
  - libre2-11=2024.07.02=h0465865_4
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.1=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h3a18249_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libxml2=2.13.9=h741aa76_0
  - libxslt=1.1.43=h25c3957_0
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.7=h4fa8253_0
  - llvmlite=0.45.1=py313h5c49287_0
  - lz4-c=1.10.0=h2466b09_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.10.8=py313hfa70ccb_0
  - matplotlib-base=3.10.8=py313he1ded55_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.3.0=hac47afa_454
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=9.3.0=h2224204_0
  - mysql-libs=9.3.0=h809f9c2_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf-fortran=4.6.1=nompi_h52e177b_104
  - numba=0.62.1=py313h7bbedcd_1
  - numpy=2.3.5=py313hce7ae62_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313hc90dcd4_2
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h3402e2f_0
  - pillow=12.0.0=py313h4212202_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - proj=9.7.1=h7b1ce8f_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py313h5fd188c_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproj=3.7.2=py313h24787ba_2
  - pyside6=6.9.2=py313h151a370_0
  - python=3.13.10=h260b955_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-eccodes=2.37.0=py313h0591002_1
  - python-gil=3.13.10=h4df99d1_100
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=3_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py313h40c08fc_1
  - pyzmq=27.1.0=py312hbb5da91_0
  - qhull=2020.2=hc790b64_5
  - qtbase=6.9.2=h06bae2a_5
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtshadertools=6.9.2=heb02b0b_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebengine=6.9.2=hebbe641_0
  - qtwebsockets=6.9.2=heb02b0b_1
  - rav1e=0.7.1=ha073cba_3
  - re2=2024.07.02=h8e466ff_4
  - setuptools=80.9.0=py313haa95532_0
  - shapely=2.1.2=py313h64ccc5a_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - sparse=0.17.0=pyhcf101f3_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.1.2=hac47afa_0
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.2=py313h5ea7bf4_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py313haa95532_0
  - xarray=2025.11.0=pyhcf101f3_0
  - xesmf=0.8.7=pyhd8ed1ab_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h534d264_6

prefix: "C:\\Users\\12ian\\anaconda3\\envs\\ATMS523-Final3.13"
